version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: tslint
    versions:
    - ">= 6.a, < 7"
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/vscode"
    versions:
    - 1.53.0
    - 1.54.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: vscode-test
    versions:
    - 1.5.0
    - 1.5.1
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
